# Generated by Django 5.2.1 on 2025-05-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_customer_user_author_post_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
