# Generated by Django 5.2.1 on 2025-05-26 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_post_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contributor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
