# Generated by Django 5.2.1 on 2025-05-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_contributor_post_contributors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contributors',
            new_name='people',
        ),
    ]
