# Generated by Django 5.2.1 on 2025-05-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_contributors_post_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='people',
            new_name='persons',
        ),
    ]
