# Generated by Django 5.2.1 on 2025-05-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_people_post_persons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='persons',
            new_name='contributors',
        ),
    ]
